version: '3.1'
services:
  dns_updater_ms:
    container_name: dns_updater_ms
    build: .
    restart: always
    environment:
      - BEARER_TOKEN=digital_ocean_token
      - PROJECT_NAME=managed_domain_second_level
      - PROJECT_NAMES=managed_domains_second_level