spring:
  application:
    name: digitalocean-record-updater
server:
  shutdown: graceful
io:
  github:
    pingmyheart:
      digitaloceanrecordupdater:
        authentication:
          digital-ocean-token: ${BEARER_TOKEN:null}
        scheduling:
          digital-ocean-sync: "0 */5 * * * *"
          public-ip-sync: "0 */3 * * * *"

info:
  app:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: "@project.version@"