config:
  authentication:
    bearer-token: ${BEARER_TOKEN:null}
  project:
    name: ${PROJECT_NAME:null}
    names: ${PROJECT_NAMES:null}
    use-multi-project: ${MULTIPROJECT_ENABLED:false}
  public-ip-site-resolver: ipinfo.io/ip # DO NOT UPDATE
  schedule:
    update-cron: "0 */5 * * * *"
server:
  shutdown: graceful
spring:
  application:
    name: DORecordUpdater-ms
  banner:
    image:
      invert: false
      pixelmode: block
      bitdepth: 8
      location: classpath:banner.png

# TEST ENVIRONMENT CONFIGURATION
---
spring:
  config:
    activate:
      on-profile: test
config:
  schedule:
    update-cron: "*/10 * * * * *"

# PROD ENVIRONMENT CONFIGURATION
---
spring:
  config:
    activate:
      on-profile: prod
  banner:
    image:
      location: classpath:banner_prod.png